# A couple of simple tests to make sure we are in an AE5 deployment
[ -d /opt/continuum ] || exit 0
[ "$APP_PORT$APP_ID" == "" ] || exit 0

for fname in $(ls $CONDA_PREFIX/lib/python*/site-packages/flask/helpers.py); do
	cat >> $fname <<EOT

# Patch to prepend all url_for URLs with a /proxy/8086 prefix
# so that Flask apps view properly in AE5 development sessions
# from that URL. This only works if *all* URLs generated by the
# app take advantage of this central url_for helper function.
_old_url_for = url_for
def url_for(endpoint, **values):
    return '/proxy/8086' + _old_url_for(endpoint, **values)
EOT
done
